export const PERMISSIONS = {
  LEADS_VIEW: "leads.view",
  LEADS_CREATE: "leads.create",
  LEADS_EDIT: "leads.edit",
  LEADS_DELETE: "leads.delete",
  LEADS_SEE_PHONE: "leads.see_phone",
  LEADS_SEE_EMAIL: "leads.see_email",
  LEADS_SEE_NOTES: "leads.see_notes",
  LEADS_ASSIGN: "leads.assign",
  LEADS_REASSIGN: "leads.reassign",
  LEADS_DELAY: "leads.delay",
  LEADS_IMPORT: "leads.import",
  LEADS_ALL_SALES: "leads.see_all_sales_leads",
  CLIENTS_VIEW: "clients.view",
  CLIENTS_EDIT: "clients.edit",
  CLIENTS_DELETE: "clients.delete",
  RESALE_VIEW: "resale.view",
  RESALE_CREATE: "resale.create",
  RESALE_EDIT: "resale.edit",
  RESALE_DELETE: "resale.delete",
  RESALE_SEE_OWNER: "resale.see_owner_info",
  RESALE_ASSIGN: "resale.assign",
  PROJECTS_VIEW: "projects.view",
  PROJECTS_MANAGE: "projects.manage",
  EMPLOYEES_VIEW: "employees.view",
  EMPLOYEES_EDIT: "employees.edit",
  EMPLOYEES_DELETE: "employees.delete",
  EMPLOYEES_APPROVE: "employees.approve",
  PERMISSIONS_MANAGE: "permissions.manage",
  REPORTS_VIEW: "reports.view",
  REPORTS_EXPORT: "reports.export",
  DASHBOARD_LIVE: "dashboard.live",
  DASHBOARD_TRACKING: "dashboard.tracking",
  NOTIFICATIONS_VIEW: "notifications.view",
  PLANNER_VIEW: "planner.view",
  PLANNER_EDIT: "planner.edit",
  PROFILE_EDIT: "profile.edit",
  PLANNER_DELETE: "planner.delete",
  LEADS_EXPORT: "leads.export",
  CLIENTS_EXPORT: "clients.export",
  CLIENTS_CREATE: "clients.create",
  RESALE_IMPORT: "resale.import",
  RESALE_EXPORT: "resale.export",
  SALES_TARGETS_VIEW: "sales_targets.view",
  SALES_TARGETS_MANAGE: "sales_targets.manage",
  AUDIT_VIEW: "audit.view",
  UPLOAD_FILES: "upload.files",
  DELAYS_VIEW: "delays.view",
  DELAYS_APPROVE: "delays.approve",
  NOTIFICATIONS_MANAGE: "notifications.manage",
  EMPLOYEES_CREATE: "employees.create",
} as const;

export type PermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS];

/**
 * Legacy/alias permission keys used by some `withPermission(...)` call sites
 * in apps/api. These do not exist in the canonical `PERMISSIONS` registry
 * above, but are normalized to a canonical key at runtime by
 * `resolver.ts`'s `PERMISSION_ALIASES` map before any DB lookup happens.
 *
 * Kept here (rather than widening `PermissionKey` itself) so the canonical
 * registry stays the single source of truth, while call sites using a known
 * alias still get compile-time safety against typos.
 *
 * IMPORTANT: this list must stay in sync with `PERMISSION_ALIASES` in
 * `resolver.ts` — every key here must have a matching entry there.
 */
export const PERMISSION_ALIAS_KEYS = [
  "leads.update",
  "leads.update_status",
  "users.view",
  "users.manage",
  "clients.create",
  "clients.update",
  "dashboard.view",
  "projects.create",
  "projects.update",
  "projects.delete",
  "resale.manage",
] as const;

export type PermissionAliasKey = typeof PERMISSION_ALIAS_KEYS[number];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, Record<string, boolean>> = {
  ceo: Object.fromEntries(Object.values(PERMISSIONS).map((p) => [p, true])),
  admin: Object.fromEntries(Object.values(PERMISSIONS).map((p) => [p, true])),
  // Director has full management permissions, mirroring CEO/Admin so they can
  // edit employees and change roles.
  director: Object.fromEntries(Object.values(PERMISSIONS).map((p) => [p, true])),

  team_leader: {
    "leads.view": true,
    "leads.create": true,
    "leads.see_phone": true,
    "leads.see_email": true,
    "leads.see_notes": true,
    "leads.assign": true,
    "leads.reassign": false,
    "clients.view": true,
    "resale.view": true,
    "employees.view": true,
    "reports.view": true,
    "dashboard.live": false,
    "notifications.view": true,
    "planner.view": true,
    "planner.edit": true,
    "profile.edit": true,
  },
  sales: {
    "leads.view": true,
    "leads.create": false,
    "leads.edit": true,
    "leads.see_phone": true,
    "leads.see_email": false,
    "leads.delay": true,
    "clients.view": true,
    "resale.view": true,
    "resale.see_owner_info": false,
    "projects.view": true,
    "employees.view": true,
    "reports.view": false,
    "dashboard.live": false,
    "notifications.view": true,
    "planner.view": true,
    "planner.edit": true,
    "profile.edit": true,
  },
};

export const PERMISSION_LABELS: Record<string, { label: string; module: string; description: string }> = {
  "leads.view": { label: "View Leads", module: "leads", description: "See leads list" },
  "leads.create": { label: "Create Leads", module: "leads", description: "Add new leads" },
  "leads.edit": { label: "Edit Leads", module: "leads", description: "Edit lead data" },
  "leads.delete": { label: "Delete Leads", module: "leads", description: "Delete leads" },
  "leads.see_phone": { label: "See Phone", module: "leads", description: "View lead phone numbers" },
  "leads.see_email": { label: "See Email", module: "leads", description: "View lead emails" },
  "leads.see_notes": { label: "See Notes", module: "leads", description: "View lead notes" },
  "leads.assign": { label: "Assign Leads", module: "leads", description: "Assign leads to sales" },
  "leads.reassign": { label: "Reassign Leads", module: "leads", description: "Reassign leads" },
  "leads.delay": { label: "Delay Leads", module: "leads", description: "Request lead delay" },
  "leads.import": { label: "Import Leads", module: "leads", description: "Bulk import via Excel" },
  "leads.see_all_sales_leads": { label: "See All Sales Leads", module: "leads", description: "View leads of all sales reps" },
  "clients.view": { label: "View Clients", module: "clients", description: "See clients list" },
  "clients.edit": { label: "Edit Clients", module: "clients", description: "Edit client data" },
  "clients.delete": { label: "Delete Clients", module: "clients", description: "Delete clients" },
  "resale.view": { label: "View Resale", module: "resale", description: "See resale units" },
  "resale.create": { label: "Create Resale", module: "resale", description: "Add resale units" },
  "resale.edit": { label: "Edit Resale", module: "resale", description: "Edit resale units" },
  "resale.delete": { label: "Delete Resale", module: "resale", description: "Delete resale units" },
  "resale.see_owner_info": { label: "See Owner Info", module: "resale", description: "View owner contact" },
  "resale.assign": { label: "Assign Resale", module: "resale", description: "Assign resale units" },
  "projects.view": { label: "View Projects", module: "projects", description: "See projects" },
  "projects.manage": { label: "Manage Projects", module: "projects", description: "Add/edit projects" },
  "employees.view": { label: "View Employees", module: "employees", description: "See employee list" },
  "employees.edit": { label: "Edit Employees", module: "employees", description: "Edit employee data" },
  "employees.delete": { label: "Delete Employees", module: "employees", description: "Delete employees" },
  "employees.approve": { label: "Approve Employees", module: "employees", description: "Approve new accounts" },
  "permissions.manage": { label: "Manage Permissions", module: "permissions", description: "Edit role permissions" },
  "reports.view": { label: "View Reports", module: "reports", description: "See analytics reports" },
  "reports.export": { label: "Export Reports", module: "reports", description: "Download reports" },
  "dashboard.live": { label: "Live Dashboard", module: "dashboard", description: "Real-time admin dashboard" },
  "dashboard.tracking": { label: "User Tracking", module: "dashboard", description: "Track user online status" },
  "notifications.view": { label: "Notifications", module: "notifications", description: "View notifications" },
  "planner.view": { label: "View Planner", module: "planner", description: "See daily planner" },
  "planner.edit": { label: "Edit Planner", module: "planner", description: "Add/edit planner tasks" },
  "profile.edit": { label: "Edit Profile", module: "profile", description: "Edit own profile" },
  "planner.delete": { label: "Delete Planner Task", module: "planner", description: "Delete planner tasks" },
  "leads.export": { label: "Export Leads", module: "leads", description: "Export leads data" },
  "clients.export": { label: "Export Clients", module: "clients", description: "Export clients data" },
  "clients.create": { label: "Create Clients", module: "clients", description: "Add new clients" },
  "resale.import": { label: "Import Resale", module: "resale", description: "Bulk import resale units" },
  "resale.export": { label: "Export Resale", module: "resale", description: "Export resale data" },
  "sales_targets.view": { label: "View Sales Targets", module: "sales_targets", description: "See sales targets" },
  "sales_targets.manage": { label: "Manage Sales Targets", module: "sales_targets", description: "Set/edit sales targets" },
  "audit.view": { label: "View Audit Logs", module: "audit", description: "Review activity audit trail" },
  "upload.files": { label: "Upload Files", module: "upload", description: "Upload attachments/photos" },
  "delays.view": { label: "View Delays", module: "delays", description: "See lead delay requests" },
  "delays.approve": { label: "Approve Delays", module: "delays", description: "Approve/reject delay requests" },
  "notifications.manage": { label: "Manage Notifications", module: "notifications", description: "Send/manage notifications" },
  "employees.create": { label: "Create Employees", module: "employees", description: "Add new employees directly" },
};
